### ISSUE TITLE
Automatically added issue reference has formatting error

### ISSUE THREAD

**Issue by p-fischer** [anfema/work#24]
When omitting the issue reference in a commit it is determined via the branch name and added automatically at the end. However, there is a syntax error in the above line break.

original commit message:
```
Title

My actual commit message ends with this line.
```

expected:
```
Title

My actual commit message ends with this line.

re #123
```

observed:
```
Title

My actual commit message ends with this line.\nre #123
```

**Comment by Somberland** [comment]
the work-tool does not provide such behaviour yet. maybe you use git hooks for this?

`.git/hooks/*`

**Comment by p-fischer** [comment]
Yes, you are right. This is not part of the work tool. It is an extra script being promoted here https://wiki.anfe.ma/dev/tooling/git-guidelines/ in the section `Automation`, which, as you said, can be used as a git hook.
